<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <customApplicationComponents>
        <alignment>right</alignment>
        <customApplicationComponent>Console.BuiltInComponent.mostRecentlyUsed</customApplicationComponent>
    </customApplicationComponents>
    <defaultLandingTab>standard-home</defaultLandingTab>
    <detailPageRefreshMethod>none</detailPageRefreshMethod>
    <enableCustomizeMyTabs>false</enableCustomizeMyTabs>
    <enableKeyboardShortcuts>true</enableKeyboardShortcuts>
    <enableListViewHover>true</enableListViewHover>
    <enableListViewReskin>true</enableListViewReskin>
    <enableMultiMonitorComponents>true</enableMultiMonitorComponents>
    <enablePinTabs>true</enablePinTabs>
    <enableTabHover>false</enableTabHover>
    <enableTabLimits>false</enableTabLimits>
    <headerColor>#FFFFFF</headerColor>
    <isServiceCloudConsole>true</isServiceCloudConsole>
    <keyboardShortcuts>
        <defaultShortcut>
            <action>FOCUS_CONSOLE</action>
            <active>true</active>
            <keyCommand>ESC</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_NAVIGATOR_TAB</action>
            <active>true</active>
            <keyCommand>V</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_DETAIL_VIEW</action>
            <active>true</active>
            <keyCommand>SHIFT+S</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_PRIMARY_TAB_PANEL</action>
            <active>true</active>
            <keyCommand>P</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_SUBTAB_PANEL</action>
            <active>true</active>
            <keyCommand>S</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_LIST_VIEW</action>
            <active>true</active>
            <keyCommand>N</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_FIRST_LIST_VIEW</action>
            <active>true</active>
            <keyCommand>SHIFT+F</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_SEARCH_INPUT</action>
            <active>true</active>
            <keyCommand>R</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>MOVE_LEFT</action>
            <active>true</active>
            <keyCommand>LEFT ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>MOVE_RIGHT</action>
            <active>true</active>
            <keyCommand>RIGHT ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>UP_ARROW</action>
            <active>true</active>
            <keyCommand>UP ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>DOWN_ARROW</action>
            <active>true</active>
            <keyCommand>DOWN ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>OPEN_TAB_SCROLLER_MENU</action>
            <active>true</active>
            <keyCommand>D</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>OPEN_TAB</action>
            <active>true</active>
            <keyCommand>T</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>CLOSE_TAB</action>
            <active>true</active>
            <keyCommand>C</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>REFRESH_TAB</action>
            <active>false</active>
            <keyCommand>SHIFT+R</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>ENTER</action>
            <active>true</active>
            <keyCommand>ENTER</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>EDIT</action>
            <active>true</active>
            <keyCommand>E</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>SAVE</action>
            <active>true</active>
            <keyCommand>CTRL+S</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>CONSOLE_LINK_DIALOG</action>
            <active>false</active>
            <keyCommand>U</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>HOTKEYS_PANEL</action>
            <active>false</active>
            <keyCommand>SHIFT+K</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_MACRO</action>
            <active>false</active>
            <keyCommand>M</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_FOOTER_PANEL</action>
            <active>false</active>
            <keyCommand>F</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_LIST_VIEW</action>
            <active>false</active>
            <keyCommand>SHIFT+N</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_LEFT_SIDEBAR</action>
            <active>false</active>
            <keyCommand>SHIFT+LEFT ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_RIGHT_SIDEBAR</action>
            <active>false</active>
            <keyCommand>SHIFT+RIGHT ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_TOP_SIDEBAR</action>
            <active>false</active>
            <keyCommand>SHIFT+UP ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_BOTTOM_SIDEBAR</action>
            <active>false</active>
            <keyCommand>SHIFT+DOWN ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_APP_LEVEL_COMPONENTS</action>
            <active>false</active>
            <keyCommand>Z</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>REOPEN_LAST_TAB</action>
            <active>false</active>
            <keyCommand>SHIFT+C</keyCommand>
        </defaultShortcut>
    </keyboardShortcuts>
    <label>Sample Agent App</label>
    <listPlacement>
        <location>full</location>
    </listPlacement>
    <listRefreshMethod>none</listRefreshMethod>
    <primaryTabColor>#0070D2</primaryTabColor>
    <pushNotifications>
        <pushNotification>
            <fieldNames>AnnualRevenue</fieldNames>
            <fieldNames>CreditScore__c</fieldNames>
            <fieldNames>CustomerAcceptanceImg__c</fieldNames>
            <fieldNames>Industry</fieldNames>
            <fieldNames>MasterRecord</fieldNames>
            <fieldNames>NumberOfEmployees</fieldNames>
            <fieldNames>PersonBirthdate</fieldNames>
            <fieldNames>PersonEmail</fieldNames>
            <fieldNames>PersonTitle</fieldNames>
            <fieldNames>Phone</fieldNames>
            <fieldNames>Website</fieldNames>
            <objectName>Account</objectName>
        </pushNotification>
        <pushNotification>
            <fieldNames>Account</fieldNames>
            <fieldNames>Comments__c</fieldNames>
            <fieldNames>Contact</fieldNames>
            <fieldNames>IsClosed</fieldNames>
            <fieldNames>Origin</fieldNames>
            <fieldNames>Reason</fieldNames>
            <fieldNames>Status</fieldNames>
            <fieldNames>Type</fieldNames>
            <objectName>Case</objectName>
        </pushNotification>
        <pushNotification>
            <fieldNames>Account</fieldNames>
            <fieldNames>Birthdate</fieldNames>
            <fieldNames>Department</fieldNames>
            <fieldNames>DoNotCall</fieldNames>
            <fieldNames>Email</fieldNames>
            <fieldNames>HomePhone</fieldNames>
            <fieldNames>MobilePhone</fieldNames>
            <fieldNames>Owner</fieldNames>
            <fieldNames>Phone</fieldNames>
            <fieldNames>Title</fieldNames>
            <objectName>Contact</objectName>
        </pushNotification>
        <pushNotification>
            <fieldNames>AnnualRevenue</fieldNames>
            <fieldNames>CreditScore__c</fieldNames>
            <fieldNames>CustomerAcceptance__c</fieldNames>
            <fieldNames>Email</fieldNames>
            <fieldNames>EnterpriseNumber__c</fieldNames>
            <fieldNames>Industry</fieldNames>
            <fieldNames>InterestIn__c</fieldNames>
            <fieldNames>MobilePhone</fieldNames>
            <fieldNames>NumberOfEmployees</fieldNames>
            <fieldNames>Status</fieldNames>
            <fieldNames>Title</fieldNames>
            <fieldNames>Website</fieldNames>
            <objectName>Lead</objectName>
        </pushNotification>
        <pushNotification>
            <fieldNames>Account</fieldNames>
            <fieldNames>Amount</fieldNames>
            <fieldNames>Bank_Name__c</fieldNames>
            <fieldNames>IBAN__c</fieldNames>
            <fieldNames>IsWon</fieldNames>
            <fieldNames>Payment_Day__c</fieldNames>
            <fieldNames>Payment_Schedule__c</fieldNames>
            <fieldNames>Payment_Specification__c</fieldNames>
            <fieldNames>Payment_Terms_Base_Days__c</fieldNames>
            <fieldNames>StageName</fieldNames>
            <fieldNames>Terms_of_Payment__c</fieldNames>
            <fieldNames>Total_Price_of_Product__c</fieldNames>
            <objectName>Opportunity</objectName>
        </pushNotification>
    </pushNotifications>
    <saveUserSessions>true</saveUserSessions>
    <tab>standard-Case</tab>
    <tab>standard-SocialPost</tab>
    <workspaceMappings>
        <mapping>
            <tab>standard-Case</tab>
        </mapping>
        <mapping>
            <tab>standard-SocialPost</tab>
        </mapping>
    </workspaceMappings>
</CustomApplication>
