/**
  * @author       : Sanchayeeta
  * @date         : 05/11/2015
  * @description  : Test Class for AccountStructure class 
  */  //test
@isTest()
public class AccountStructureTest{
     
    //private static testMethod void TestMet(){

    //   system.Test.startTest();  
    //   //Account acc= new Account();
    //   List<Account> testAccountList = CXE_TestDataFactory.createBusinessAccount(1);
    //   Account acc = testAccountList.get(0);
    //   acc.name='Test Acc';
    //   acc.Customer_Accepted__c = 'Rejected';
    //   insert acc;
    //    AccountStructure acctstrct = new AccountStructure();
    //    Boolean[] levelFlag;
    //    //levelFlag.add(true);
    //    Boolean[] closeFlag;
    //    //closeFlag.add(true);
    //    List<String> nodeElements = new List<String>();
    //    nodeElements.add('1');
    //    AccountStructure.ObjectStructureMap acctstrctObj = new AccountStructure.ObjectStructureMap('Test',levelFlag,closeFlag ,'Test', true, false, acc);
    //    //List<AccountStructure.ObjectStructureMap> acctstrctObjlist = new List<AccountStructure.ObjectStructureMap>;
    //    PageReference pageRef = Page.AccountHierarchyPage;  
    //    system.Test.setCurrentPage(pageRef);
    //     System.currentPageReference().getParameters().put('id', acc.Id); 
        
    //    acctstrctObj.getnodeId();
    //    acctstrctObj.getlevelFlag();
    //    acctstrctObj.getcloseFlag();
    //    acctstrctObj.getnodeType();
    //    acctstrctObj.getcurrentNode();
    //    acctstrctObj.getaccount();
    //    acctstrctObj.setnodeId('Test');
    //    //acctstrctObj.setlevelFlag( true ); 
    //    acctstrctObj.setnodeType('Test');
    //    acctstrctObj.setcurrentNode(true);
    //    acctstrctObj.setaccount(acc);
    //    acctstrct.setcurrentId('Test');
    //    acctstrct.formatObjectStructure(acc.id);
    //    acctstrct.GetTopElement(acc.id);
    //    acctstrct.isLastNode(nodeElements);
    //    acctstrct.setcloseFlag(nodeElements,nodeElements,'Test');
    //    acctstrct.setlevelFlag(nodeElements,'Test');
    //    //acctstrct.getObjectStructure();
    //}
   
}