@istest(seealldata=true)
public class BundleConfigurator_test {
    
//private static testmethod void BundleConfigurator_test()
// {
//      PageReference pageref = Page.bundleConfigurator;
//        System.Test.setCurrentPage(pageref);
//      account acc=TestDataFactoryTest.createAccount('test account');
//      opportunity opp= TestDataFactoryTest.createOpportunity(acc.id,'test opportunity',system.today(),'prospecting',null,null);
//     connection__C conn=TestDataFactoryTest.createConnection('test connection','12345');
//     conn.Utility_type__c='electricity';
//     update conn;
//      connection__C conn2=TestDataFactoryTest.createConnection('test connection 2','123456');
//     conn.Utility_type__c='Gas';
//     update conn2;
//     pricebook2 pb2=TestDataFactoryTest.createPricebook(true,'bundlepricebook');
//     product2 BundleProduct=TestDataFactoryTest.createBundleProduct('test bundle product',pb2.id);
    
//     apexPages.currentPage().getParameters().put('id', opp.id);
//     BundleConfiguratorController BCT=new BundleConfiguratorController();
//     BCT.selbundle=BundleProduct.id;
//     bct.newConnectionSelected(conn);
//     bct.newConnectionSelected(conn2);
//     bct.bundleProducts();
//     bct.newcon();
//     bct.getthis();
//     bct.save();
//     bct.calculateeav();
//     bct.closepopup();
//     bct.clearmap();
//     bct.cancel();
//     bct.showpopup();
//     product2 expectedbundle=bct.getProductDetail();
    
// }

}