/**
 * @author Aard-Jan van Kesteren
 * @description All constants that are used in multiple classes. 
 */
public class Constants {

    // Notification statusses
    public static final String NOTIFICATION_STATUS_DRAFT = 'Draft';
    public static final String NOTIFICATION_STATUS_PUBLISHED = 'Published';
 
    // User Notification statusses
    public static final String USER_NOTIFICATION_STATUS_NEW = 'New';
    public static final String USER_NOTIFICATION_STATUS_DISPLAYED = 'Displayed';
    public static final String USER_NOTIFICATION_STATUS_OPENED = 'Opened';
    public static final String USER_NOTIFICATION_STATUS_READ = 'Read';
    
    ///  user variables 
    public static final String USR_TMP_EMAIL = 'us.name@vmail.com';
    public static final String ENCODE_KEY = 'UTF-8';
    public static final String TIME_ZONE = 'America/Los_Angeles';
    public static final String LOCALE_KEY = 'en_US';
    public static final String USER_POSTFIX = '@testorg.com';
    
    /// Sobject Specific Constants
    public static final string QUOTE_STATUS_ACCEPTED = 'Accepted';
    public static final string OPP_STAGE_CLOSED_WON = 'Closed Won';
    
    // Product Item Value Types
    public static final String PRODUCT_ITEM_VALUE_TYPE_RATE = 'Rate';
    public static final String PRODUCT_ITEM_VALUE_TYPE_PERCENTAGE = 'Percentage';
    public static final String PRODUCT_ITEM_VALUE_TYPE_NONE = 'None';
}