/**
  * @author       : Christopher
  * @date         : 02/05/2016
  * @description  : Test Class for AccoForceOrderId trigger 
  */  
@isTest()
public class ForceOrderIdTest{
/*
     
    private static testMethod void TestForceId(){

       system.Test.startTest();
        Account acc= new Account();
           acc.name='Test Acc';
           acc.Customer_Accepted__c = 'Rejected';
           insert acc;  
       Order ord = new Order();
       ord.Accountid=acc.id;
       ord.EffectiveDate=System.today();
       ord.Status='Draft';
       insert ord;
       Axsy__Sales_Transaction__c  ast= new Axsy__Sales_Transaction__c ();
        ast.Axsy__Amount__c =10; 
           insert ast;
        
    }*/
   
}