/* Description: LightningSelfRegisterController_Test test class
 * Author: Christian Peter Doctolero
 * Date Created: MAR-31-17
 */
@isTest
private class LightningSelfRegisterController_Test {
    
    static testMethod void selfRegisterTest()
    {
        String fName = 'John';
        String lName = 'Doe';
        String email = 'username@email.com';
        String password = 'testPassword';
        String confirmPassword = 'testPassword';
        String accId = '001';
        String regConfirmUrl = 'testurl.com';
        String extraFields = 'extra';
        String startUrl = 'www';

    }
}