/**
*  Test Class for Lightning_CommodityProdConfCtrl
*  @Author Accenture 
*  Created date : 22/03/2016
*  Version Changes  
* 
* 
*/
@isTest(seealldata=true)
public class Lightning_Lightning_CommProdConfCtrlTest {
//static testMethod void testLightning_CommodityProdConfCtrl() {
//    Account a = CXE_TestDataFactory.createBusinessAccount(1)[0];
//    insert a;
//    Opportunity opp = new Opportunity(Name=a.Name + ' Opportunity ' ,StageName='Prospecting',CloseDate=System.today().addMonths(1),AccountId=a.Id);
//    insert opp;
    
//    List<Lightning_CommodityProductsConfigCntrl.eavQA> s1 = new  List<Lightning_CommodityProductsConfigCntrl.eavQA>();
//    String str1 = JSON.serialize(s1);

//    List<Lightning_CommodityProductsConfigCntrl.connectionWrapper1> s2 = new  List<Lightning_CommodityProductsConfigCntrl.connectionWrapper1>();
//    String str2 = JSON.serialize(s2);
   
    
    
//    List<Lightning_CommodityProdConfCtrl.Wrapper> wrap = Lightning_CommodityProdConfCtrl.getQA(opp.id);
//    list<Lightning_CommodityProductsConfigCntrl.connectionWrapper1> WrapLis = Lightning_CommodityProdConfCtrl.genEAV(str1,str2 );
//    }
    }