/**
  * @author       : Sanchayeeta
  * @date         : 05/11/2015
  * @description  : Test Class for QuoteSyncUtil class 
  */  
@isTest
public class QuoteSyncUtilTest{
     
    //private static testMethod void TestMet(){
            
    //    Account Acc=TestDataFactoryTest.createAccount('test Account');
    //    pricebook2 BundlePricebook=TestDataFactoryTest.createPricebook('testPricebook',true);  
    //    product2 Bundleprod=TestDataFactoryTest.createBundleProduct(' test bundle ',BundlePricebook.id);
    //    Connection__C con=TestDataFactoryTest.createConnection('Test','20');
    //    Connection__C con1=TestDataFactoryTest.createConnection('Test1','20');
    //    opportunity opp1=TestDataFactoryTest.createOpportunity(acc.id,'test opportunity ',system.today(),'close Won ',BundlePricebook.id,Bundleprod.id);
    //    Quote quo= TestDataFactoryTest.createQuote(opp1.id,Acc.id,'TestQuote',BundlePricebook.id);
    //    PriceBookEntry pbe= [select id from PriceBookEntry where Product2id=: Bundleprod.id and Pricebook2Id=:quo.Pricebook2Id limit 1];           
    //    QuoteLineItem qli= TestDataFactoryTest.createQuoteLIneItem(quo.id,pbe.id,2,5.0,con.id);
    //    Set<ID> setQuote = new Set<ID>();
    //    setQuote.add(quo.id);
    //    system.Test.startTest(); 
    //    QuoteSyncUtil oQuote = new QuoteSyncUtil();
    //    setQuote=QuoteSyncUtil.getNewQuoteIds();
    //    QuoteSyncUtil.removeNewQuoteId(quo.id);
    //    QuoteSyncUtil.clearNewQuoteIds();             
    //    String st= QuoteSyncUtil.getQuoteLineFieldMapTo('ID');
    //    String str=QuoteSyncUtil.getQuoteFieldMapTo('ID') ;
    //    String str1=QuoteSyncUtil.addQuoteField('ID','QuoteId');
    //    String str2=QuoteSyncUtil.addQuoteLineField('ID', 'id');
    //    String str3=QuoteSyncUtil.removeQuoteLineField('ID');
    //    String str4=QuoteSyncUtil.removeQuoteField('ID');
    //    Schema.DescribeFieldResult q = QuoteSyncUtil.getField('Quote', 'id');
    //    Schema.DescribeFieldResult q1 = QuoteSyncUtil.getField('QuoteLineItem', 'id');
    //    Schema.DescribeFieldResult q2 = QuoteSyncUtil.getField('OpportunityLineItem', 'id');
    //    //Schema.DescribeFieldResult q3 = QuoteSyncUtil.getField('test', 'id');
    //    qli.Connection__C=con1.id;
    //    update qli;
    //    system.Test.stopTest();
        
    
    
    //}
}